### ISSUE TITLE
Не поднялся Docker в Ubuntu 20.10.2 LTS

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/content#158]
1. Устанавливаем Git `sudo apt install git`
2. Устанавливаем Docker [по инструкции](https://docs.docker.com/engine/install/ubuntu/)
3. Скачиваем репозиторий content
4. Заходим в папку с контентом
5. Запускаем команду `docker-compose pull && docker-compose up`
6. Получаем ошибку

    ```bash
    ERROR: The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services 'platform'
    ```

**Comment by igsekor** [comment]
Кажется, что есть несколько моментов:
1. В настоящей инструкции отсутствует пункт установки Docker Compose (на Linux — это отдельный [гайд](https://docs.docker.com/compose/install/)).
2. Можно запустить контейнер и без Docker Compose.
3. В разных Linux в официальных репозиториях поддерживаются разные версии Docker Engine и Docker Compose. В репозитории Ubuntu 20.12.2 LTS поддерживается старая версия. Появляются разночтения.
4. Есть ли смысл усложнять, если не планируется совместно запускать несколько контейнеров?

Мой вариант: оставить простой контейнер и запускать его с помощью команды:
docker run -p 127.0.0.1:80:8080/tcp ydoka/platform

Даже скачивать ничего не придется...

Инструкция будет тогда такой:
1. Устанавливаем Git sudo apt install git
2. Устанавливаем Docker [по инструкции](https://docs.docker.com/engine/install/ubuntu/)
3. Выполняем команду: docker run -p 127.0.0.1:80:8080/tcp ydoka/platform

**Comment by furtivite** [comment]
@nlopin @pepelsbey

**Comment by furtivite** [comment]
![2021-03-19_21-13-03](https://user-images.githubusercontent.com/50330458/111824993-fc87f400-88f7-11eb-8807-b26348bf1df5.png)

Решение работает.

**Comment by furtivite** [comment]
Ещё тесты

1. Винда
![photo_2021-03-19 21 41 40](https://user-images.githubusercontent.com/50330458/111828170-f3992180-88fb-11eb-84ad-e8e667182282.jpeg)
2. Мак
![photo_2021-03-19 21 41 34](https://user-images.githubusercontent.com/50330458/111828165-f1cf5e00-88fb-11eb-829e-93771d61f49e.jpeg)
3. Убунту
![photo_2021-03-19 21 41 37](https://user-images.githubusercontent.com/50330458/111828168-f3008b00-88fb-11eb-9bce-a36e80eedfea.jpeg)

Сам контент почему-то на Ubuntu не тянется

**Comment by igsekor** [comment]
А если так?

docker run -rm -p 127.0.0.1:80:8080/tcp -v "$(pwd)"/:/platform/content ydoka/platform

**Comment by furtivite** [comment]
`docker run --rm -p 127.0.0.1:80:8080/tcp -v "$(pwd)"/:/platform/content ydoka/platform`

работает. Обновлю документацию

**Comment by igsekor** [comment]
Если решение подойдет, может быть есть смысл выпилить docker-compose.yml, чтобы не смущать народ?
