### ISSUE TITLE
Определиться, кеш или кэш

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/content#186]
- [ ] Поискать и нормализовать в контенте
- [ ] Поправить в исключениях спеллера

**Comment by tachisis** [comment]
По правилам мы должны писать **е**.

- [Розенталь](http://old-rozental.ru/orfografia.php?sid=8#pp8);
- [Об употреблении букв э и е после согласных в словах иноязычного происхождения](https://cyberleninka.ru/article/n/ob-upotreblenii-bukv-e-i-e-posle-soglasnyh-v-slovah-inoyazychnogo-proishozhdeniya/viewer) (размышление о вариативности с заключением, что в итоге все придет к уже принятым нормам, то есть е);
- [8 слов, в которых мы произносим «э», но писать должны «е»](https://mel.fm/pravopisaniye/9840512-foreign_words) (демонстрирует склонность к нормативности).

Но в [Большом толковом словаре Кузнецова](http://gramota.ru/slovari/dic/?all=x&word=%D0%9A%D0%AD%D0%A8) закреплен вариант к**э**ш, как и в нескольких других словарях, в том числе, в Словаре иностранных слов русского языка.

Зафиксированное в словарях имеет приоритет над общим формальным правилом, так что предлагаю писать **кэш**.

**Comment by pepelsbey** [comment]
Огонь, тогда ждём пулреквест :)
