### ISSUE TITLE
Row: строка или ряд?

### ISSUE THREAD

**Issue by tachisis** [Y-Doka/content#236]
В процессе чтения лонга про флексы и про гриды заметила, что из-за перевода **row** как «строка» может возникнуть неясность — речь идет о ряде элементов или о текстовой строке.

У меня есть предложение в таких случаях использвать слово «ряд». Это чуть менее расхоже по сравнению с общеупотребительным «строка таблицы», но у нас не таблицы, и кажется, что будет меньше путаницы.

Примеры:

> Свойство распределяет свободное пространство по поперечной оси между строками флекс-элементов. Предположим, у вас 11 элементов на 3 строках. Если размер родителя по поперечной оси позволяет, то при помощи `align-content` можно распределять строчки элементов: по верхнему краю, по нижнему, по центру или равномерно.
> 
> Не имеет видимого значения, если элементы располагаются в одну строку.
> 
> Возможные значения:
> 
> - `stretch` (значение по умолчанию) — строки растягиваются одинаково, так, чтобы занять всё доступное пространство родителя.
> - `flex-start` / `start` — все строки располагаются у начала поперечной оси. Первое значение не зависит от направления чтения текущего языка, в отличие от второго.
> - `flex-end` / `end` — все строки располагаются у конца поперечной оси. `end` «уважает» направление чтения текущего языка.
> - `center` — строки выравниваются по центру родителя.
> - `space-between` — первая строка прижимается к началу поперечной оси, последняя — к концу поперечной оси, а остальные располагаются так, чтобы свободное пространство было поделено на отступы между ними равномерно.
> - `space-around` — отступы у каждой строки равнозначны отступам у любой другой строки.
> - `space-evenly` — отступы между строками и от краёв родителя одинаковые.

> Принцип работы гридов чем-то похож на таблицы. Вместо работы только со строками или колонками с их помощью можно работать с так называемыми ячейками, позиционируя элементы по вертикали и горизонтали одновременно.

**Comment by tachisis** [comment]
Призываю @solarrust, @pepelsbey и других заинтересованных высказаться

**Comment by solarrust** [comment]
Да, супер предложение. «Ряд» звучит очень хорошо и позволяет избежать разночтений 👍

**Comment by pepelsbey** [comment]
Ряды и колонки FTW

**Comment by tachisis** [comment]
Всем спасибо, тогда создам PR на изменения.
