### ISSUE TITLE
Улучшение документации для авторов

### ISSUE THREAD

**Issue by tachisis** [Y-Doka/content#298]
- Переписать README так, чтобы там были все необходимые ссылки для контрибьюторов (авторов)
- Перенести в README вводную часть из файла contributing.md (до «Как работает дока»)
- «Как работает Дока» сделать отдельным материалом и таким образом избавиться от файла contributing.md
- Разобрать writing.md на «Руководство по стилю» и «Справочник по оформлению»
- Создать документ «В помощь автору», перенести туда советы из https://www.notion.so/praktikum/1c069beeb97d4a479826311441a5faab и рекомендации по литературе

**Comment by nlopin** [comment]
В «Как работает Дока» много технических деталей, может их пернесем в реп платформы? Второй вариант — выкинуть их совсем, потому что в новом репозитории все немного по новому

**Comment by pepelsbey** [comment]
Файл CONTRIBUTING.md это такая же важная условность, что и README.md, так что я бы его сохранил и наполнил коротким понятным со ссылками на полную документацию. Чтобы это была такая точка входа.

**Comment by pepelsbey** [comment]
В остальном согласен :)

**Comment by tachisis** [comment]
Добавила первую версию Руководства по стилю, призываю всех заинтересованных прочитать и прокомментировать! https://github.com/Y-Doka/content/blob/edit/298-author-docs/docs/STYLEGUIDE.md
