### ISSUE TITLE
Что такое файл

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/content#379]
Рассказать про коцепцию файла, про относительные и абсолютные пути

**Comment by nlopin** [comment]
@igsekor поделись мыслями

**Comment by igsekor** [comment]
@nlopin думаю, что надо рассказать про файловые системы без воды, немного про историю, немного про альтернативы. Затем хорошо бы раскрыть основные типы файловых систем, их виды, какие используются в операционных системах и основные особенности. Потом естественно нужно и практики добавить. Классно вот здесь демки сделать, наверное. Обдумаю, вынесу на обсуждение.
