### ISSUE TITLE
Архитектура приложения

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/content#382]
Про подходы и паттерны проектирования (MVC, MVVM, etc.)

**Comment by nlopin** [comment]
@bespoyasov из этой темы стоит развить серию статей. Как думаешь?

**Comment by bespoyasov** [comment]
![Ребята, я в этом шарю](https://user-images.githubusercontent.com/9102374/116540793-4a2e4e00-a8f3-11eb-89c6-11d8d6f4dd2c.jpeg)

Да! С удовольствием бы взял.

**Comment by bespoyasov** [comment]
А мы хотим здесь именно поговорить в целом об архитектуре или же отдельные паттерны проектирования (адаптер, фасад, стратегия и т. д.) тоже хотим взять? Можно сперва даже ограничиться только структурными паттернами как вариант.

**Comment by nlopin** [comment]
Я думаю начнем со структурных и продолжим остальными

**Comment by bespoyasov** [comment]
Предлагаю вот такой план:

- Обзорная статья об архитектуре и паттернах (зачем, чем отличаются друг от друга);
  - MVC, MVVM, MV-whatever;
  - Чистая архитектура по Мартину;
  - Монолит vs Микросервисы;
  - Реактивные изменения vs однонаправленный поток данных;
- Обзорная статья о паттернах проектирования (структурные, поведенческие, создательные);
  - Часто-используемые структурные паттерны (адаптер, фасад, прокси, мост, декоратор);
  - Часто-используемые создательные паттерны (фабрика, билдер, абстрактная фабрика, синглтон[?]);
  - Часто-используемые поведенческие паттерны (стратегия, цепь ответственности, команда, медиатор, обсервер, итератор).

Что добавить?

**Comment by nlopin** [comment]
Мне нравится план, но я бы вначале больше бы говорил о высокоуровневых паттернах, которые критически важно знать во фронтенде: о реактивных изменениях, о FLUX архитектуре (это вроде однонаправленный поток данных в твоей терминологии), монолитах и микросервисах (или микрофронтендах?)

Я ожидаю, что читатель в первую очередь будет высокоуровнево понимать, как организован фронтенд приложения с точки зрения архитектуры. Вторым уровнем — понимать бэк и его паттерны, третьим уже паттерны организации кода

**Comment by bespoyasov** [comment]
Ну там всё так и есть, о бекенде ни слова не было 😃

**Comment by bespoyasov** [comment]
Я не могу поменять описание ишьи, чтобы добавить туду-список в него. @nlopin, поможешь?

**Comment by bespoyasov** [comment]
Ещё подумал, что нас не нужно две обзорные статьи отдельно об архитектуре и паттернах. 

Обзорную сделаю всё же одну: так будет проще показывать разницу, пользу и всё прочее. 

Отдельные статьи будут уже конкретно по каждому из подходов.

Сегодня начну писать обзорную.

**Comment by nlopin** [comment]
> Ну там всё так и есть, о бекенде ни слова не было 😃

Для меня тот же MVC кажется больше про бэк. Хотя он неявно везде торчит

**Comment by nlopin** [comment]
> Я не могу поменять описание ишьи, чтобы добавить туду-список в него. @nlopin, поможешь?
> 
> Ну либо, если изменить описание нельзя, то давай закроем эту и откроем новую со списком статей?

Открою отдельные. Прямо по списку выше создавать или хочешь что-то изменить?

**Comment by bespoyasov** [comment]
> Для меня тот же MVC кажется больше про бэк. Хотя он неявно везде торчит
 
Backbone.js передаёт привет 😃

> Открою отдельные. Прямо по списку выше создавать или хочешь что-то изменить?

Немного, да. Давай вот такой список сделаем:

- [x] Архитектура и паттерны проектирования (https://github.com/Y-Doka/content/pull/515)
- [ ] Архитектура MVC, MVVM, MC-whatever
- [ ] Трёхслойная архитектура
- [ ] Организация потоков данных
- [ ] Монолиты и микросервисы
- [ ] Паттерны проектирования, создательные
- [ ] Паттерны проектирования, структурные
- [ ] Паттерны проектирования, поведенческие

**Comment by nlopin** [comment]
Создал отдельные задачи, эту закрываю
