### ISSUE TITLE
Перенести статьи по инструментам

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/content#7]
- [x] Git CLI — минимум для работы
- [x] Node.js — дом инструментов разработки
- [x] Webpack, краткий обзор
- [x] Как TypeScript и статическая типизация помогает писать код
- [x] Код-ревью — как, зачем, почему
- [x] Пакетные менеджеры
- [x] Системы сборки
- [x] Системы управления версиями
- [x] Статический анализ — как делать меньше ошибок
- [x] Что такое Docker?
- [x] Что такое Node.js?
- [x] Что такое методологии разработки и Agile
- [x] Как устроен Dockerfile

**Comment by furtivite** [comment]
Статьи из списка перенесены, если появятся новые статьи, их перенесём отдельно.
