### ISSUE TITLE
Не хватает статей из раздела JS

### ISSUE THREAD

**Issue by skorobaeus** [Y-Doka/content#730]
— Array.reduce (есть в [старом репо](https://github.com/Y-Doka/y-doka.site/blob/master/src/posts/js/doka/array-reduce.md));
— Element (есть в [ноушн](https://www.notion.so/praktikum/Element-21832f417bf74e898ff604fb94697899))

**Comment by nlopin** [comment]
@skorobaeus Element есть https://new.y-doka.site/js/doka/element/
