### ISSUE TITLE
Ограничить проверку изменённых файлов только нужными

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/content#751]
Сейчас мы делаем

```
Проверка для ${changed_file}
```

Что иногда приводит к

```
Проверка для tools/articles/webserver/images/1.png
Error: /home/runner/work/content/content/tools/articles/webserver/images/1.png: is not UTF-8
```

Надо где-то на уровне цикла отфильтровать только `*.{md,html}`, как мы делаем в другой ветке условия.

Также я бы добавил для спеллера ключ `--only-errors`, чтобы проще было читать логи, когда проверяются все файлы.

**Comment by igsekor** [comment]
Проблема решена в связанном PR.
