### ISSUE TITLE
Определиться с написанием слова скевоморфизма

### ISSUE THREAD

**Issue by nikolai-shabalin** [Y-Doka/content#795]
В проекте встречаются "скевоморфизм" и "скеоморфизм".

Я бы придерживался "Скевоморфизм", только потому что [Википедия](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%B5%D0%B2%D0%BE%D0%BC%D0%BE%D1%80%D1%84%D0%B8%D0%B7%D0%BC)

**Comment by tachisis** [comment]
@pepelsbey что тут требуется от меня? Скевоморфизм одобряю.

**Comment by pepelsbey** [comment]
@tachisis найти и убедиться, что у нас в контенте используется именно «скевоморфизм» :) Если нет, то прислать пулреквест и с чувством удовлетворения закрыть эту задачу.

**Comment by tachisis** [comment]
Проверила, в ветке main на настоящий момент ни одного «скеоморфизма» нет. В словарь добавлена правильная форма. Закрываю ишью.
